services:
  mcp-jira:
    container_name: mcp-jira
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - n8n_default

networks:
  n8n_default:
    external: true